#-------------------------------
# General Site Settings
baseURL = "https://elisevolkman.com/"
languageCode = "en-us"
title = "Maja Hampson (the best)"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 6


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Maja Hampson, author of Middle Grade and Young Adult SFF, repped by the Epic Kaitlyn."
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Books"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 6
    hasChildren = true

      # Footer Menu
      [[menu.footer]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

      [[menu.footer]]
      identifier = "projects"
      name = "Books"
      url = "/projects/"
      weight = 2

      [[menu.footer]]
      identifier = "services"
      name = "Services"
      url = "/services/"
      weight = 3

      [[menu.footer]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 4

      [[menu.footer]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 5

      [[menu.footer]]
      identifier = "blog"
      name = "Blog"
      url = "/posts/"
      weight = 6

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Maja Hampson"
    author__bio = "I'm an author who is also a superhero. Don't tell anyone."
    author__avatar = "/images/maja.jpg"

  # Social Links
  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://www.instagram.com/maja_is_writing/"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = ""

  [[params.social]]
    icon = "ion-logo-linkedin"
    name = "LinkedIn"
    link = ""

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "YouTube"
    link = ""

  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = ""

  # Example of adding a new link to the footer:
  # [[params.social]]
  #   icon = "ion-logo-youtube"
  #   name = "Youtube"
  #   link = "https://youtube.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Author repped by Kaitlyn of the Epic Literary Agency I definitely remember the name of."
    hero__description = "These ARE the books you're looking for."
    hero__image = "/images/maja.jpg"

  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__identifier = "" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address..."
    mailchimp__button__text = "Get Updates" # Add your button text


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true
    projects__title= "Books"
    projects__description= "Middle Grade SFF, Picture Books, and BIOLOGY"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "Kind Words"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Elise Volkman"
    image = "/images/elise.jpg"
    designation = "Author of The Nymph Keepers"
    link = "https://elisevolkman.com/"
    content = "We have the same website because I'm a great friend."

  [[params.testimonial_item]]
    name = "Elise Volkman"
    image = "/images/elise.jpg"
    designation = "Author of The Nymph Keepers"
    link = "https://elisevolkman.com/"
    content = "My books will scar you emotionally. Maja's books will make you feel like a kid again. Pick your poison."

  [[params.testimonial_item]]
    name = "Elise Volkman"
    image = "/images/elise.jpg"
    designation = "Author of The Nymph Keepers"
    link = "https://elisevolkman.com/"
    content = "Worship the Maja and all will be well."

  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Blog"
    blog__description = "I write about writing about writing sometimes."


  #-------------------------------
  # Gallery Footer Settings
  [params.gallery]
    enable = true

  [[params.gallery_image]]
    image_alt = "Mug of tea beside writing tablet on blue background"
    image_url = "/images/maja-horse.jpg"

  [[params.gallery_image]]
    image_alt = "Writing tablet on top of several open books"
    image_url = "/images/maja-lion.jpg"

  [[params.gallery_image]]
    image_alt = "The Tea Grannies, Miraya and Elise, smiling"
    image_url = "/images/maja-rhino.jpg"

  [[params.gallery_image]]
    image_alt = "Book 'Through Fire and Ruin' on top of writing tablet on black background"
    image_url = "/images/maja-lemurs.jpg"


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "mjvznjnv" # Add your form_id

    # NOTE
    # Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false